// Generated by Wrangler / Cloudflare bindings
interface Env {
  // Cloudflare environment bindings
  ASSETS?: Fetcher;

  // Environment variables and secrets
  NODE_ENV?: "development" | "production" | "test";
  SITE_URL?: string;
  DATABASE_URL?: string;
  CLERK_SECRET_KEY?: string;
  ADMIN_CLERK_USER_ID?: string;
}
